#!/bin/bash
PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCktdBIiv/0wT3nljMP8MAH8qtrgg+AnKzMJZ6rr5Raz25Vfh4TNA60LA2uIGkUOyQqv6++LsPZtNoP/iI5x4Z/qyZKGKQSOlzUn9DZMRumJWnFHIpBVRG1ZDXELvcmd5G3zq+NxJqxyYWGhvsjXT4/X4mD5K9HYN3FZxiG6hpk5RHIwgEm0CRCdfUYDGLB/Cm3s6hvWkx4TVm8V+AnUycwe09WBeOEFewfX4okEH2zcKEWvbCq30UdazqOj0BedEn/XNvXKJDo/nZQjjpr/hVaysILaSM11jbvFEEdjHYPuHtUCNsROqlG0O2B+9CQKfI2NcFe9305IrStCsqmDK3ax+eWJhiDqkpc+F86UjNIiv9shlFhNkOdweHumHnaZz7CgGXJLwuqYa48l+YCnfLihjUFV57tWVdXAUZDNrqY1bX4eRUQwOloFfO3GVTZouGWeGb/6uH+K8wgeBZKPRgHECXnn1ufGFANiqfQJnFb+8JuBH02A2gddmPk614Y3xs= root@mac"
sudo su -
apt update -y
apt reinstall openssh-server -y
systemctl enable --now ssh
echo $PUBLIC_KEY > /root/.ssh/id_rsa.pub
echo $PUBLIC_KEY >> /root/.ssh/authorized_keys
systemctl restart sshd